runtime: go120
main: ./cmd/server
service_account: pictmanager@ikedam.iam.gserviceaccount.com

automatic_scaling:
  max_instances: 1

env_variables:
  PICTMANAGER_GCS: gs://ikadam-picts

handlers:
  - url: /api/admin/.*
    script: auto
    secure: always
    redirect_http_response_code: 301
    login: admin
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /(.*\.(css|ico|js|txt))$
    static_files: static/\1
    upload: static/.*\.(css|ico|js|txt)$
    secure: always
    redirect_http_response_code: 301
  - url: .*
    static_files: static/index.html
    upload: static/index.html
    secure: always
    redirect_http_response_code: 301
