version: '3'
services:
  server:
    image: golang:1.20.4-bullseye
    environment:
      - http_proxy
      - https_proxy
      - no_proxy=storage,firestore,${no_proxy:-}
      - CLOUDSDK_CORE_PROJECT=pictmanager
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - STORAGE_EMULATOR_HOST=storage:4443
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - firestore
      - storage
  firestore:
    build:
      context: docker/firestore
      args:
        - http_proxy
        - https_proxy
    environment:
      - CLOUDSDK_CORE_PROJECT=pictmanager
    volumes:
      - /data
    ports:
      # firebase UI が firestore にクライアントから接続させるので firestore もポートの公開が必要
      - 8080:8080
      - 4000:4000
  storage:
    image: fsouza/fake-gcs-server:1.44.2
    volumes:
      - ./docker/storage:/storage
    command:
      - -scheme
      - http
      - -public-host
      - storage:4443
  terraform:
    profiles: [dummy]
    image: hashicorp/terraform:1.4.6
    volumes:
      - ./terraform:/workspace
      - ${CLOUDSDK_CONFIG:-}:/root/.config/gcloud
    working_dir: /workspace
